In [4]:
import numpy as np

In [68]:
np.__version__

'1.20.1'

In [69]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Rana/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Rana/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Rana/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Rana/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Rana/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Rana/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Rana/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Rana/anaconda3\\Library\\include']


In [70]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [71]:
a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])
print(a)
print(b)

[1 2 3]
[[1 2]
 [3 4]]


In [72]:
a.size

3

In [73]:
b.size

4

In [74]:
np.info

<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x0000020DA41CEBB0>, toplevel='numpy')>

In [75]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [76]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [77]:
a = np.arange(10)
print(a)
a = a[::-1]
print(a)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [78]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [79]:
a = np.array([1,2,0,4,0,5])
print(a[np.nonzero(a)])

[1 2 4 5]


In [80]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
np.random.random((3,3,3))

array([[[0.90939985, 0.30525559, 0.40287162],
        [0.26483071, 0.15676282, 0.8579007 ],
        [0.68854263, 0.34004299, 0.13033248]],

       [[0.99917685, 0.92636735, 0.312     ],
        [0.84330819, 0.45308805, 0.60469265],
        [0.61438471, 0.66607743, 0.14176991]],

       [[0.9397749 , 0.80414872, 0.72145528],
        [0.32663007, 0.62444562, 0.52713571],
        [0.39126489, 0.08506476, 0.12890193]]])

In [82]:
matrix = np.random.rand(10,10)
print(matrix)
print(matrix.min())
print(matrix.max())

[[8.17129922e-01 6.15684591e-01 5.53545802e-01 7.02346256e-02
  1.14385648e-01 4.73932359e-01 5.07484434e-02 9.71530788e-01
  4.06135633e-01 4.05035540e-01]
 [1.03836359e-01 5.09233696e-01 2.54598699e-01 2.93932240e-01
  6.62700588e-01 3.27212741e-01 6.91543138e-01 7.15857695e-01
  8.15690347e-01 7.60539570e-01]
 [5.16558693e-01 2.80696109e-01 1.55505807e-01 7.40407400e-01
  4.15576395e-01 8.36374834e-01 7.75282229e-01 1.68943720e-02
  8.55056122e-01 4.03327994e-01]
 [1.82324291e-01 6.85147448e-02 6.60577089e-01 8.82544916e-01
  1.24699097e-01 1.59794079e-01 1.76144461e-01 5.40210328e-01
  2.97841337e-01 7.12539763e-01]
 [9.87960780e-01 7.29645503e-01 2.34121873e-01 1.55007709e-01
  3.06502387e-04 3.15958439e-01 6.52191472e-01 1.79988978e-01
  7.16217911e-01 9.41387528e-01]
 [7.35996539e-01 2.82162339e-01 4.18248511e-01 1.36173788e-02
  9.51448035e-01 1.01184160e-01 7.46180337e-01 9.06484973e-01
  4.06062889e-01 6.78040265e-01]
 [4.24452218e-01 7.11967583e-01 8.69915041e-02 5.33186597e

a = np.random.rand(30)

In [83]:
a = np.random.rand(30)
print(a)

[0.85741505 0.676418   0.9386117  0.09078388 0.91666694 0.87516578
 0.74040827 0.21589462 0.12264475 0.83268983 0.44245464 0.76544464
 0.66140921 0.89419397 0.88340469 0.07550451 0.93223604 0.78263732
 0.22731738 0.22963556 0.95529614 0.75606225 0.15937084 0.06706466
 0.23948978 0.77573187 0.16141101 0.87442401 0.22766409 0.30089505]


In [84]:
a.mean()

0.5559448827864432

In [2]:
print("a")

a


In [12]:
a = np.ones((8,8))
print(a)
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
