In [1]:
import numpy as np

In [126]:
np.__version__

'1.20.1'

In [127]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Rana/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Rana/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Rana/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Rana/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Rana/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Rana/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Rana/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Rana/anaconda3\\Library\\include']


In [128]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [129]:
a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])
print(a)
print(b)

[1 2 3]
[[1 2]
 [3 4]]


In [130]:
a.size

3

In [131]:
b.size

4

In [132]:
np.info

<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x0000022A1809FBB0>, toplevel='numpy')>

In [133]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [134]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [135]:
a = np.arange(10)
print(a)
a = a[::-1]
print(a)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [136]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [137]:
a = np.array([1,2,0,4,0,5])
print(a[np.nonzero(a)])

[1 2 4 5]


In [138]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [139]:
np.random.random((3,3,3))

array([[[0.67717803, 0.00858825, 0.31503502],
        [0.67580175, 0.07325578, 0.69497044],
        [0.68990718, 0.48088098, 0.91657685]],

       [[0.2055421 , 0.5493224 , 0.99997435],
        [0.75879863, 0.12706771, 0.93982918],
        [0.35410055, 0.76990667, 0.78115072]],

       [[0.12672337, 0.91163985, 0.65841576],
        [0.8201394 , 0.28021832, 0.95585441],
        [0.9076998 , 0.6582698 , 0.44192419]]])

In [140]:
matrix = np.random.rand(10,10)
print(matrix)
print(matrix.min())
print(matrix.max())

[[0.59212019 0.56768023 0.0436473  0.62280259 0.60380576 0.92966828
  0.07157926 0.5662716  0.04018216 0.36503257]
 [0.51728315 0.93048412 0.52014936 0.68079004 0.80109934 0.2739696
  0.32086664 0.88197488 0.39175174 0.99947954]
 [0.21135515 0.99514145 0.11950334 0.17806239 0.17936157 0.37257207
  0.92401127 0.28030118 0.67092817 0.18491742]
 [0.92647888 0.6753047  0.82122579 0.11498975 0.69931844 0.99914818
  0.62632001 0.28887078 0.7564654  0.01192607]
 [0.64501856 0.28083785 0.6529236  0.87963556 0.6224341  0.62681544
  0.38295379 0.4311561  0.88759808 0.05150424]
 [0.43760905 0.29920369 0.38575717 0.6827114  0.84127809 0.05681039
  0.48191741 0.86847402 0.61931203 0.62795404]
 [0.88391865 0.38403867 0.05494364 0.05185159 0.68432955 0.9469573
  0.5451798  0.43135226 0.62566753 0.9338695 ]
 [0.45773772 0.24565267 0.78428992 0.15648276 0.86298392 0.05819273
  0.25801172 0.31551541 0.10064556 0.84747149]
 [0.04727657 0.70755519 0.00587621 0.99521193 0.04395679 0.2884602
  0.14193745 0.

a = np.random.rand(30)

In [141]:
a = np.random.rand(30)
print(a)

[0.64718971 0.46568582 0.14684723 0.24902019 0.47610352 0.78798216
 0.5154668  0.50640705 0.10274798 0.66775583 0.53020952 0.81920396
 0.26336247 0.77863157 0.70313679 0.31358399 0.11476875 0.13432595
 0.67570795 0.77977733 0.11943706 0.20538503 0.42259315 0.98583385
 0.85421046 0.80346838 0.57472153 0.71258585 0.55632576 0.61326907]


In [142]:
a.mean()

0.517524823335197

In [143]:
print("a")

a


In [144]:
a = np.ones((8,8))
print(a)
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [145]:
a = np.ones((4,4))
b = np.pad(a, pad_width = 1, mode = 'constant', constant_values = 0)
print(b)
a[:,[0,-1]] = 0
print(a)
a[[0,-1],:] = 0
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]]
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [146]:
0*np.nan
print(0*np.nan)
np.nan == np.nan
print(np.nan == np.nan)
np.nan - np.nan
print(np.nan - np.nan)
np.nan in set([np.nan])
print(np.nan in set([np.nan]))
0.3 == 3*0.1
print(0.3 == 3*0.1)

nan
False
nan
True
False


In [147]:
a = np.diag(1+np.arange(4), k = -1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [148]:
a = np.zeros((8,8), dtype = int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [149]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [150]:
a = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [151]:
a = np.random.random((5,5))
a = (a - np.mean(a)) / (np.std(a))
print(a)

[[-1.15758394  1.38215171 -0.149434    0.30751473 -1.52183903]
 [-0.06305215 -0.96749109  1.36279921  1.27682328 -1.46603793]
 [ 1.44372647  0.75862772 -1.0242088  -0.6065238   0.86851779]
 [ 0.0984005  -1.25933532 -0.97650577  0.24166165  0.71802405]
 [ 0.10354258 -1.49649231 -0.08995495  1.29632495  0.92034443]]


In [152]:
colour = np.dtype([("r", np.ubyte),("g", np.ubyte),("b", np.ubyte),("a", np.ubyte)])
print(colour)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [153]:
a = np.dot(np.ones((5,3)),np.ones((3,2)))
print(a)
a = np.ones((5,3)) @ np.ones((3,2))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [154]:
a = np.arange(12)
print(a)
a[(3<a) & (a<8)] *= -1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11]


In [155]:
print(sum(range(5),-1))
from numpy import*
print(sum(range(5),-1))

10
10


In [156]:
Z = 3
Z**Z
print(Z**Z)
2 << Z >> 2
print(2 << Z >> 2)
Z <- Z
print(Z <- Z)
1j*Z
print(1j*Z)
Z/1/1
print(Z/1/1)
Z<Z>Z
print(Z<Z>Z)

27
4
False
3j
3.0
False


In [157]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


In [158]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z))
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[-8.16075969 -2.21914815  8.79685222  1.39636799  8.93247429  2.88449232
  6.37987958 -2.910286    8.59412317 -5.40445249]
[-9. -3.  9.  2.  9.  3.  7. -3.  9. -6.]
[-9. -3.  9.  2.  9.  3.  7. -3.  9. -6.]


In [159]:
Z1 = np.random.randint(0,10,10)
print(Z1)
Z2 = np.random.randint(0,10,10)
print(Z2)
print(np.intersect1d(Z1,Z2))

[6 9 7 6 2 9 3 9 0 3]
[6 7 9 5 3 5 8 4 4 6]
[3 6 7 9]


In [160]:
defaults = np.seterr(all = "ignore")
print(np.ones(1)/1)
_= np.seterr("defaults")

[1.]


KeyError: 'defaults'

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

In [ ]:
yesterday = np.datetime64('today') - np.timedelta64(1)
print(yesterday)
today = np.datetime64('today')
print(today)
tomorrow = np.datetime64('today') + np.timedelta64(1)
print(tomorrow)

In [ ]:
b = np.arange('2021-06','2021-07',dtype='datetime64[D]')
print(b)

In [ ]:
a = np.ones(4)*1
b = np.ones(4)*3
print(a)
print(b)
np.add(a,b,out=b)
print(b)
np.divide(a,2,out=a)
print(a)
np.negative(a,out=a)
print(a)
np.multiply(a,b,out=a)
print(a)

In [ ]:
a = np.random.uniform(2,8,5)
print(a)
print(a -a%1)
print(a // 1)
print(a.astype(int))
print(np.trunc(a))

In [ ]:
a = np.zeros((5,5))
a += np.arange(5)
print(a)
a = np.tile(np.arange(5),(5,1))
print(a)

In [ ]:
def formation_fun():
    for x in arange(10):
        yield x
a = np.fromiter(formation_fun(),dtype=int,count=-1)
print(a)

In [ ]:
a = np.linspace(0,1,11,endpoint = False)[1:]
print(a)

In [ ]:
a = np.random.random(10)
print(a)
a.sort()
print(a)

In [4]:
a = np.arange(12)
np.add.reduce(a)

66

In [8]:
a = np.random.randint(4,5,8)
b = np.random.randint(4,5,8)
equal = np.allclose(a,b)
print(equal)
equal = np.array_equal(a,b)
print(equal)

True
True


In [15]:
a = np.ones(10)
print(a)
a.flags.writeable = False

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [20]:
a = np.random.random((8,2))
print(a)
b = a[:,0]
c = a[:,1]
print(b)
print(c)
d = np.sqrt(b**2 + c**2)
print(d)
e = np.arctan2(c,b)
print(e)

[[0.21952949 0.23424723]
 [0.31306901 0.30392019]
 [0.56104419 0.56683651]
 [0.19602015 0.75719057]
 [0.60360425 0.91584309]
 [0.38408639 0.51373665]
 [0.32719949 0.90734311]
 [0.35935454 0.09148485]]
[0.21952949 0.31306901 0.56104419 0.19602015 0.60360425 0.38408639
 0.32719949 0.35935454]
[0.23424723 0.30392019 0.56683651 0.75719057 0.91584309 0.51373665
 0.90734311 0.09148485]
[0.32103732 0.43632521 0.79754261 0.78215182 1.09686219 0.64144189
 0.96453669 0.37081688]
[0.81782068 0.77057109 0.79053369 1.31747931 0.98807176 0.92881192
 1.2246984  0.24928556]


In [24]:
a = np.random.randint(2,20,12)
print(a)
a[a.argmax()] = 0
print(a)

[ 2 19 16 19 12 11  9 14  8 14  5  6]
[ 2  0 16 19 12 11  9 14  8 14  5  6]


In [34]:
a = np.zeros((5,5), [('b',float),('c',float)])
print(a)
a['b'] = np.meshgrid(np.linspace(0,2,5))
print(a)
a['c'] = np.meshgrid(np.linspace(0,2,5))
print(a)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0. , 0.) (0.5, 0.) (1. , 0.) (1.5, 0.) (2. , 0.)]
 [(0. , 0.) (0.5, 0.) (1. , 0.) (1.5, 0.) (2. , 0.)]
 [(0. , 0.) (0.5, 0.) (1. , 0.) (1.5, 0.) (2. , 0.)]
 [(0. , 0.) (0.5, 0.) (1. , 0.) (1.5, 0.) (2. , 0.)]
 [(0. , 0.) (0.5, 0.) (1. , 0.) (1.5, 0.) (2. , 0.)]]
[[(0. , 0. ) (0.5, 0.5) (1. , 1. ) (1.5, 1.5) (2. , 2. )]
 [(0. , 0. ) (0.5, 0.5) (1. , 1. ) (1.5, 1.5) (2. , 2. )]
 [(0. , 0. ) (0.5, 0.5) (1. , 1. ) (1.5, 1.5) (2. , 2. )]
 [(0. , 0. ) (0.5, 0.5) (1. , 1. ) (1.5, 1.5) (2. , 2. )]
 [(0. , 0. ) (0.5, 0.5) (1. , 1. ) (1.5, 1.5) (2. , 2. )]]


In [40]:
a = np.arange(10)
print(a)
b = a + 0.5
print(b)
print(np.subtract.outer(a,b))
c = 1.0/np.subtract.outer(a,b)
print(c)
print(np.linalg.det(c))

[0 1 2 3 4 5 6 7 8 9]
[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
[[-0.5 -1.5 -2.5 -3.5 -4.5 -5.5 -6.5 -7.5 -8.5 -9.5]
 [ 0.5 -0.5 -1.5 -2.5 -3.5 -4.5 -5.5 -6.5 -7.5 -8.5]
 [ 1.5  0.5 -0.5 -1.5 -2.5 -3.5 -4.5 -5.5 -6.5 -7.5]
 [ 2.5  1.5  0.5 -0.5 -1.5 -2.5 -3.5 -4.5 -5.5 -6.5]
 [ 3.5  2.5  1.5  0.5 -0.5 -1.5 -2.5 -3.5 -4.5 -5.5]
 [ 4.5  3.5  2.5  1.5  0.5 -0.5 -1.5 -2.5 -3.5 -4.5]
 [ 5.5  4.5  3.5  2.5  1.5  0.5 -0.5 -1.5 -2.5 -3.5]
 [ 6.5  5.5  4.5  3.5  2.5  1.5  0.5 -0.5 -1.5 -2.5]
 [ 7.5  6.5  5.5  4.5  3.5  2.5  1.5  0.5 -0.5 -1.5]
 [ 8.5  7.5  6.5  5.5  4.5  3.5  2.5  1.5  0.5 -0.5]]
[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333 -0.11764706 -0.10526316]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615 -0.13333333 -0.11764706]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818 -0.15384615 -0.13333333]
 [ 0.4         0.66666667  2. 

In [42]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [46]:
a = np.arange((1,5),5)
print
np.set_printoptions(threshold = float("inf"))
a = np.ones((10,10))
print(a)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
