In [4]:
import numpy as np

In [68]:
np.__version__

'1.20.1'

In [69]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Rana/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Rana/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Rana/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Rana/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Rana/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Rana/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Rana/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Rana/anaconda3\\Library\\include']


In [70]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [71]:
a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])
print(a)
print(b)

[1 2 3]
[[1 2]
 [3 4]]


In [72]:
a.size

3

In [73]:
b.size

4

In [74]:
np.info

<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x0000020DA41CEBB0>, toplevel='numpy')>

In [75]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [76]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [77]:
a = np.arange(10)
print(a)
a = a[::-1]
print(a)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [78]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [79]:
a = np.array([1,2,0,4,0,5])
print(a[np.nonzero(a)])

[1 2 4 5]


In [80]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
np.random.random((3,3,3))

array([[[0.90939985, 0.30525559, 0.40287162],
        [0.26483071, 0.15676282, 0.8579007 ],
        [0.68854263, 0.34004299, 0.13033248]],

       [[0.99917685, 0.92636735, 0.312     ],
        [0.84330819, 0.45308805, 0.60469265],
        [0.61438471, 0.66607743, 0.14176991]],

       [[0.9397749 , 0.80414872, 0.72145528],
        [0.32663007, 0.62444562, 0.52713571],
        [0.39126489, 0.08506476, 0.12890193]]])

In [82]:
matrix = np.random.rand(10,10)
print(matrix)
print(matrix.min())
print(matrix.max())

[[8.17129922e-01 6.15684591e-01 5.53545802e-01 7.02346256e-02
  1.14385648e-01 4.73932359e-01 5.07484434e-02 9.71530788e-01
  4.06135633e-01 4.05035540e-01]
 [1.03836359e-01 5.09233696e-01 2.54598699e-01 2.93932240e-01
  6.62700588e-01 3.27212741e-01 6.91543138e-01 7.15857695e-01
  8.15690347e-01 7.60539570e-01]
 [5.16558693e-01 2.80696109e-01 1.55505807e-01 7.40407400e-01
  4.15576395e-01 8.36374834e-01 7.75282229e-01 1.68943720e-02
  8.55056122e-01 4.03327994e-01]
 [1.82324291e-01 6.85147448e-02 6.60577089e-01 8.82544916e-01
  1.24699097e-01 1.59794079e-01 1.76144461e-01 5.40210328e-01
  2.97841337e-01 7.12539763e-01]
 [9.87960780e-01 7.29645503e-01 2.34121873e-01 1.55007709e-01
  3.06502387e-04 3.15958439e-01 6.52191472e-01 1.79988978e-01
  7.16217911e-01 9.41387528e-01]
 [7.35996539e-01 2.82162339e-01 4.18248511e-01 1.36173788e-02
  9.51448035e-01 1.01184160e-01 7.46180337e-01 9.06484973e-01
  4.06062889e-01 6.78040265e-01]
 [4.24452218e-01 7.11967583e-01 8.69915041e-02 5.33186597e

a = np.random.rand(30)

In [83]:
a = np.random.rand(30)
print(a)

[0.85741505 0.676418   0.9386117  0.09078388 0.91666694 0.87516578
 0.74040827 0.21589462 0.12264475 0.83268983 0.44245464 0.76544464
 0.66140921 0.89419397 0.88340469 0.07550451 0.93223604 0.78263732
 0.22731738 0.22963556 0.95529614 0.75606225 0.15937084 0.06706466
 0.23948978 0.77573187 0.16141101 0.87442401 0.22766409 0.30089505]


In [84]:
a.mean()

0.5559448827864432

In [2]:
print("a")

a


In [12]:
a = np.ones((8,8))
print(a)
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [19]:
a = np.ones((4,4))
b = np.pad(a, pad_width = 1, mode = 'constant', constant_values = 0)
print(b)
a[:,[0,-1]] = 0
print(a)
a[[0,-1],:] = 0
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]]
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [20]:
0*np.nan
print(0*np.nan)
np.nan == np.nan
print(np.nan == np.nan)
np.nan - np.nan
print(np.nan - np.nan)
np.nan in set([np.nan])
print(np.nan in set([np.nan]))
0.3 == 3*0.1
print(0.3 == 3*0.1)

nan
False
nan
True
False


In [31]:
a = np.diag(1+np.arange(4), k = -1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [48]:
a = np.zeros((8,8), dtype = int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [52]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [55]:
a = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [59]:
a = np.random.random((5,5))
a = (a - np.mean(a)) / (np.std(a))
print(a)

[[ 0.98184111 -0.27035694 -0.62570797  0.28431586 -1.31021655]
 [ 0.20798082 -1.11223296  0.96927235 -1.09853701 -0.81844662]
 [ 0.87847381 -0.01509726  0.50196933  1.49109983  0.00850656]
 [ 1.11224703  0.96517879 -1.11558592 -0.77847744  1.33329121]
 [ 0.97943435 -0.79435201 -1.60363828 -1.57823409  1.40727197]]


In [60]:
colour = np.dtype([("r", np.ubyte),("g", np.ubyte),("b", np.ubyte),("a", np.ubyte)])
print(colour)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [62]:
a = np.dot(np.ones((5,3)),np.ones((3,2)))
print(a)
a = np.ones((5,3)) @ np.ones((3,2))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [64]:
a = np.arange(12)
print(a)
a[(3<a) & (a<8)] *= -1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11]


In [66]:
print(sum(range(5),-1))
from numpy import*
print(sum(range(5),-1))

9
10


In [68]:
Z = 3
Z**Z
print(Z**Z)
2 << Z >> 2
print(2 << Z >> 2)
Z <- Z
print(Z <- Z)
1j*Z
print(1j*Z)
Z/1/1
print(Z/1/1)
Z<Z>Z
print(Z<Z>Z)

27
4
False
3j
3.0
False


In [69]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-69-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-69-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [75]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z))
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ 9.1350675  -0.30211994 -4.37732761  6.83304746 -7.49701506  2.75820887
 -8.80031589  2.42523976 -4.68948903  6.69734333]
[10. -1. -5.  7. -8.  3. -9.  3. -5.  7.]
[10. -1. -5.  7. -8.  3. -9.  3. -5.  7.]


In [77]:
Z1 = np.random.randint(0,10,10)
print(Z1)
Z2 = np.random.randint(0,10,10)
print(Z2)
print(np.intersect1d(Z1,Z2))

[1 0 3 9 1 9 4 1 9 5]
[4 6 7 3 6 7 3 1 3 2]
[1 3 4]


In [80]:
defaults = np.seterr(all = "ignore")
print(np.ones(1)/1)
_= np.seterr("defaults")

[1.]


KeyError: 'defaults'

In [81]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [86]:
yesterday = np.datetime64('today') - np.timedelta64(1)
print(yesterday)
today = np.datetime64('today')
print(today)
tomorrow = np.datetime64('today') + np.timedelta64(1)
print(tomorrow)

2021-06-12
2021-06-13
2021-06-14


In [90]:
b = np.arange('2021-06','2021-07',dtype='datetime64[D]')
print(b)

['2021-06-01' '2021-06-02' '2021-06-03' '2021-06-04' '2021-06-05'
 '2021-06-06' '2021-06-07' '2021-06-08' '2021-06-09' '2021-06-10'
 '2021-06-11' '2021-06-12' '2021-06-13' '2021-06-14' '2021-06-15'
 '2021-06-16' '2021-06-17' '2021-06-18' '2021-06-19' '2021-06-20'
 '2021-06-21' '2021-06-22' '2021-06-23' '2021-06-24' '2021-06-25'
 '2021-06-26' '2021-06-27' '2021-06-28' '2021-06-29' '2021-06-30']


In [95]:
a = np.ones(4)*1
b = np.ones(4)*3
print(a)
print(b)
np.add(a,b,out=b)
print(b)
np.divide(a,2,out=a)
print(a)
np.negative(a,out=a)
print(a)
np.multiply(a,b,out=a)
print(a)

[1. 1. 1. 1.]
[3. 3. 3. 3.]
[4. 4. 4. 4.]
[0.5 0.5 0.5 0.5]
[-0.5 -0.5 -0.5 -0.5]
[-2. -2. -2. -2.]


In [104]:
a = np.random.uniform(2,8,5)
print(a)
print(a -a%1)
print(a // 1)
print(a.astype(int))
print(np.trunc(a))

[7.18662032 4.2518809  2.95073582 5.54843253 4.50555038]
[7. 4. 2. 5. 4.]
[7. 4. 2. 5. 4.]
[7 4 2 5 4]
[7. 4. 2. 5. 4.]


In [108]:
a = np.zeros((5,5))
a += np.arange(5)
print(a)
a = np.tile(np.arange(5),(5,1))
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [113]:
def formation_fun():
    for x in arange(10):
        yield x
a = np.fromiter(formation_fun(),dtype=int,count=-1)
print(a)

[0 1 2 3 4 5 6 7 8 9]
