In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.1'

In [4]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Rana/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Rana/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Rana/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Rana/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Rana/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Rana/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Rana/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Rana/anaconda3\\Library\\include']


In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])
print(a)
print(b)

[1 2 3]
[[1 2]
 [3 4]]


In [14]:
a.size

3

In [15]:
b.size

4

In [16]:
np.info

<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x0000020DA41CEBB0>, toplevel='numpy')>

In [22]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [26]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [35]:
a = np.arange(10)
print(a)
a = a[::-1]
print(a)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [39]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [44]:
a = np.array([1,2,0,4,0,5])
print(a[np.nonzero(a)])

[1 2 4 5]


In [49]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
np.random.random((3,3,3))

array([[[0.89521219, 0.45142313, 0.05794908],
        [0.65822492, 0.75045128, 0.94565699],
        [0.2616482 , 0.15607681, 0.16651619]],

       [[0.21548336, 0.17095019, 0.3413726 ],
        [0.91796056, 0.31394049, 0.20967283],
        [0.30919794, 0.61798801, 0.44791965]],

       [[0.460569  , 0.00743077, 0.87084432],
        [0.95523981, 0.32452116, 0.88403374],
        [0.93053635, 0.85192685, 0.94257285]]])

In [63]:
matrix = np.random.rand(10,10)
print(matrix)
print(matrix.min())
print(matrix.max())

[[0.00851702 0.34184856 0.78598325 0.94231816 0.3389478  0.16212658
  0.97572457 0.63973185 0.51882755 0.28607941]
 [0.2202886  0.50045029 0.75778437 0.98416884 0.22711713 0.15953312
  0.47969117 0.13538304 0.17492806 0.11901113]
 [0.96653339 0.6673023  0.81884868 0.31828197 0.53228775 0.87951424
  0.24273171 0.86140163 0.76024937 0.27162255]
 [0.5739139  0.36231488 0.43487119 0.51054209 0.2976831  0.95101675
  0.76936095 0.16602374 0.90866521 0.54904309]
 [0.62105548 0.07023074 0.54397311 0.84603673 0.79325412 0.42103746
  0.45699609 0.13874411 0.28835171 0.24753413]
 [0.63536928 0.02236469 0.52328934 0.1680221  0.2945416  0.74561748
  0.35111489 0.47911367 0.34401216 0.41514234]
 [0.74546591 0.66575023 0.45160084 0.47188499 0.76188796 0.22454015
  0.81967879 0.93037881 0.21776975 0.621242  ]
 [0.05052771 0.71339521 0.08224402 0.39685141 0.30298676 0.26738169
  0.55543691 0.14167659 0.68914643 0.05006839]
 [0.21716786 0.07976938 0.08957913 0.73133617 0.42643026 0.72979944
  0.51488213

a = np.random.rand(30)

In [65]:
a = np.random.rand(30)
print(a)

[0.25649252 0.29477999 0.16994784 0.04799597 0.88741242 0.73465053
 0.66402873 0.87490282 0.43155094 0.39122511 0.78690713 0.03318218
 0.2345387  0.05375912 0.63629663 0.62242505 0.44430183 0.98465537
 0.95031675 0.22933714 0.25323465 0.63271337 0.14731143 0.25650294
 0.84858418 0.42442174 0.48108588 0.92068674 0.17132382 0.62761546]
